# Generated by Django 5.1.2 on 2024-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_Preferences',
            fields=[
                ('prefrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('preferred_region', models.CharField(max_length=100)),
                ('preferred_exchage', models.CharField(max_length=100)),
                ('risk_tolerance', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('asset_type', models.IntegerField(choices=[(1, 'Stocks'), (2, 'Bonds'), (3, 'Options')], default=1)),
            ],
            options={
                'db_table': 'Investment_Prefrences',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
