# Generated by Django 5.1.2 on 2024-11-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investment_preferences',
            table='Investment_Preferences',
        ),
    ]
