# Generated by Django 5.1.2 on 2024-11-12 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 19, 54, 30, 363255)),
        ),
    ]
