# Generated by Django 5.1.2 on 2024-11-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0002_rename_id_users_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarked_stock',
            name='stock_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookmarked_stock',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investment_prefrences',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='stock_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
