# Generated by Django 5.1.2 on 2024-11-12 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0002_alter_stocks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 19, 55, 11, 440513)),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 19, 55, 11, 440513)),
        ),
    ]
