# Generated by Django 5.1.2 on 2024-11-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0002_alter_investment_preferences_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_preferences',
            old_name='preferred_exchage',
            new_name='preferred_exchange',
        ),
    ]
