# Generated by Django 5.1.2 on 2024-11-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0003_rename_preferred_exchage_investment_preferences_preferred_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Investment_Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefrence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.investment_preferences')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.stocks')),
            ],
            options={
                'db_table': 'stock_investment_preferences',
            },
        ),
        migrations.CreateModel(
            name='User_Bookmarked_Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.stocks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.users')),
            ],
            options={
                'db_table': 'user_bookmarked_stocks',
            },
        ),
        migrations.CreateModel(
            name='User_Investment_Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefrence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.investment_preferences')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.users')),
            ],
            options={
                'db_table': 'user_investment_preferences',
            },
        ),
    ]
