# Generated by Django 5.1.3 on 2024-11-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srsApp", "0003_alter_bookmarked_stock_stock_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Investment_Prefrences",
            new_name="Investment_Preferences",
        ),
        migrations.AlterModelTable(
            name="investment_preferences",
            table="Investment_Preferences",
        ),
    ]
