# Generated by Django 5.1.3 on 2024-11-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0004_bookmarkedstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarked_stock',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.stocks'),
        ),
        migrations.AlterField(
            model_name='bookmarked_stock',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srsApp.users'),
        ),
        migrations.DeleteModel(
            name='BookmarkedStock',
        ),
    ]
