# Generated by Django 5.1.3 on 2024-11-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("srsApp", "0004_rename_investment_prefrences_investment_preferences_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investment_preferences",
            old_name="preferred_exchage",
            new_name="preferred_exchange",
        ),
    ]
