# Generated by Django 5.1.2 on 2024-11-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0004_stock_investment_preferences_user_bookmarked_stocks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_bookmarked_stocks',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='user_bookmarked_stocks',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='user_bookmarked_stocks',
            unique_together={('user', 'stock')},
        ),
    ]
