# Generated by Django 5.1.3 on 2024-11-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "srsApp",
            "0005_rename_preferred_exchage_investment_preferences_preferred_exchange",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="sector",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="stocks",
            name="stock_symbol",
            field=models.CharField(max_length=255),
        ),
    ]
