# Generated by Django 5.1.2 on 2024-11-15 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srsApp', '0006_rename_prefrence_id_stock_investment_preferences_preference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment_preferences',
            old_name='prefrence_id',
            new_name='preference_id',
        ),
    ]
